// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABmZwPPgrmeSXgJVWV6wppIBDvFfrKkzk',
    appId: '1:378839797068:web:7cc6147d8858c99522d3e9',
    messagingSenderId: '378839797068',
    projectId: 'listsplit-76ded',
    authDomain: 'listsplit-76ded.firebaseapp.com',
    databaseURL: 'https://listsplit-76ded-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'listsplit-76ded.appspot.com',
    measurementId: 'G-2NR7GTN5JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtc0dAa5AojEOOT7MJK-74VZpsUeeenIo',
    appId: '1:378839797068:android:0a26ab62ee3d73f922d3e9',
    messagingSenderId: '378839797068',
    projectId: 'listsplit-76ded',
    databaseURL: 'https://listsplit-76ded-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'listsplit-76ded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKWCndpkdqFtV01HCGTd8g3ARHhxmOWyU',
    appId: '1:378839797068:ios:f02a01cdf1936b0522d3e9',
    messagingSenderId: '378839797068',
    projectId: 'listsplit-76ded',
    databaseURL: 'https://listsplit-76ded-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'listsplit-76ded.appspot.com',
    iosClientId: '378839797068-e7c7uh3pouh7m0m1p6785vfhte5rq3ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKWCndpkdqFtV01HCGTd8g3ARHhxmOWyU',
    appId: '1:378839797068:ios:f02a01cdf1936b0522d3e9',
    messagingSenderId: '378839797068',
    projectId: 'listsplit-76ded',
    databaseURL: 'https://listsplit-76ded-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'listsplit-76ded.appspot.com',
    iosClientId: '378839797068-e7c7uh3pouh7m0m1p6785vfhte5rq3ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
